language: rust
rust:
  - nightly
services:
  - postgresql
env:
  - PATH=$PATH:/home/travis/.cargo/bin
install:
  - cargo install diesel_cli
before_script:
  - psql -c 'create database pasters;' -U postgres
  - diesel setup
