[package]
name = "pasters"
version = "0.1.0"
authors = ["Gramy <jan.keim@protonmail.com>"]

[dependencies]
rocket = "0.1.2"
rocket_codegen = "0.1.2"
rand = "0.3"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
